### ISSUE TITLE
View not Centre Aligned

### ISSUE THREAD

**Issue by Taimoor20** [zhxf2012/CropImageView#2]
The library is working perfectly fine. I am facing an issue that the view of CropImageView is not centre aligned. I am attaching a photo [https://ibb.co/Kj38DVj](url). If you see at the trailing side, the **Done** button  is very close to the screen of the mobile and if you see at the leading side, there is a white space. Why is it not centre aligned?

**Comment by zhxf2012** [comment]
Merged and fixed
